### PR TITLE
Methylseq documentation

### PR DESCRIPTION
**Pull request by fortune9**
Added demo methylseq report as well as how-to-read document

### CODE REVIEW

**Comment by fortune9** [comment]
@zxl124 I added the how to read document for the methylseq data, please let me know if any conflicts. If not, I can move forward to merge the request. Thanks.

**Comment by zxl124** [comment]
@fortune9 Things looked good. One question, you added another advanced report, but didn't refer to it. Do you plan to add documentations regarding that later?

**Comment by fortune9** [comment]
> 
> 
> @fortune9 Things looked good. One question, you added another advanced report, but didn't refer to it. Do you plan to add documentations regarding that later?

Yes. The how-to doc for advanced isn't finished yet. Will refer to it later. Thanks.

**Review by zxl124 — APPROVED** [review]

**Comment by zxl124** [comment]
Go ahead and merge then.

**Pull request merged**
